steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      ["builds", "submit", "--tag", "gcr.io/wisepot/azbuka"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "azbuka",
        "--image",
        "gcr.io/wisepot/azbuka",
        "--region",
        "europe-west1",
        "--platform",
        "managed",
        "--min-instances",
        "0",
        "--allow-unauthenticated"
      ]