import postcss from "postcss";
import { writeFile } from "fs/promises";

import { getUsages } from "./processor.js";
import { getStylesByClassName } from "./inventory.js";

export async function generateOutputCSS(config) {
  const cache = {};
  const usages = getUsages();
  Object.keys(usages).map((file) => {
    Object.keys(usages[file]).forEach(async (label) => {
      try {
        createMediaStyle(config, label, usages[file][label], cache);
      } catch (err) {
        console.error(`Error generating media query for label ${label} (found in file ${file}): ${err}`);
      }
    });
  });
  const result = Object.keys(cache)
    .map((label) => cache[label].mq.toString())
    .join("\n");
  if (config.output) {
    await writeFile(config.output, `/* ForgeCSS autogenerated file */\n${result}`, "utf-8");
  }
  return result;
}
export function createMediaStyle(config, label, selectors, cache) {
  if (!config.mapping.queries[label]) {
    throw new Error(
      `Unknown media query label: ${label}. Check app-fe/wwwroot/scripts/lib/generateMediaQueries.js for available mappings.`
    );
  }
  if (!cache[label]) {
    cache[label] = {
      mq: postcss.atRule({
        name: "media",
        params: `all and (${config.mapping.queries[label].query})`
      }),
      classes: {}
    };
  }
  const mq = cache[label].mq;
  selectors.forEach((selector) => {
    const prefixedSelector = `.${label}_${selector}`;
    if (cache[label].classes[prefixedSelector]) {
      return;
    }
    cache[label].classes[prefixedSelector] = true;
    const rule = postcss.rule({ selector: prefixedSelector });
    const decls = getStylesByClassName(selector);
    if (decls.length === 0) {
      console.warn(`Warning: No styles found for class .${selector} used in media query ${label}`);
      return;
    }
    decls.forEach((d) => {
      rule.append(
        postcss.decl({
          prop: d.prop,
          value: d.value,
          important: d.important
        })
      );
    });
    mq.append(rule);
  });
}